"""empty message

Revision ID: 02457a3e54ed
Revises: 4259a9dfeeb2
Create Date: 2021-12-08 15:36:11.110715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02457a3e54ed'
down_revision = '4259a9dfeeb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('style_model', sa.Column('name', sa.String(length=60), nullable=True))
    op.drop_index('style', table_name='style_model')
    op.create_unique_constraint(None, 'style_model', ['name'])
    op.drop_column('style_model', 'style')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('style_model', sa.Column('style', mysql.VARCHAR(length=60), nullable=True))
    op.drop_constraint(None, 'style_model', type_='unique')
    op.create_index('style', 'style_model', ['style'], unique=False)
    op.drop_column('style_model', 'name')
    # ### end Alembic commands ###
