"""empty message

Revision ID: 8bc5df9c6e92
Revises: 3b93fd8d5bd8
Create Date: 2021-12-06 18:49:24.179184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc5df9c6e92'
down_revision = '3b93fd8d5bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('from_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'from_admin')
    # ### end Alembic commands ###
